name: Update Daily Aggregates CSV

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Website Repository
      uses: actions/checkout@v2

    - name: Download CSV from Scraper Repo
      run: |
        curl -o docs/data/daily.csv https://raw.githubusercontent.com/hidegmisi/us2024_aggregator_scraper/refs/heads/main/daily_aggregates.csv

    - name: Commit and Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update daily_aggregates file new data"
        file_pattern: '*.csv'
        disable_globbing: true
