name: Update Daily Aggregates CSV

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Website Repository
      uses: actions/checkout@v2

    - name: Download CSV from Scraper Repo
      run: |
        curl -o docs/data/daily.csv https://raw.githubusercontent.com/hidegmisi/us2024_aggregator_scraper/refs/heads/main/daily_aggregates.csv

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/data/daily.csv
        git commit -m "Update daily aggregates CSV from scraper"
        git push
